### ISSUE TITLE
Adding or missing tooltip options

### ISSUE THREAD

**Issue by ghost** [linuxmint/python-xapp#9]
Greetings I have been testing the newer Settings controls on an app, and I have been checking that not all of them have tooltips available when creating them via code, here are some examples:

Button control that has tooltips (lightdm-settings as example):
![Tooltip1](https://user-images.githubusercontent.com/1509924/59371261-c3bdf280-8d01-11e9-846c-76d2c80b2ec1.png)

![Tooltip2](https://user-images.githubusercontent.com/1509924/59371262-c3bdf280-8d01-11e9-9d11-718f4c426c7e.png)

Button control that doesn't has tooltips (mintdesktop as example):
![Tooltip3](https://user-images.githubusercontent.com/1509924/59371503-6bd3bb80-8d02-11e9-8ef4-f91d0f3a5f55.png)

The "ComboBox" seems that it has tooltips. Am I missing something to declare via code?
![Tooltip4](https://user-images.githubusercontent.com/1509924/59371504-6bd3bb80-8d02-11e9-81a9-ea5c48dc351a.png)

Maybe I am missing something or perhaps there is a declaration that I need to do on the code, but it would be great if you can add that support to all the newer controls that you created or may be planning to create

**Comment by ghost** [comment]
I answer myself after a lot of testing, in order to add a new tooltip it is a little bit interesting on how xapps and GTK mixed up into inheriting some of the properties of the control (and yeah, sorry for being ignorant but I stumble across after testing)

Now maybe I should open this as another incident, but do you have any documentation related to python-xapps on how to add or use the controls in order to add some examples or at least some information to keep in mind?

**Comment by clefebvre** [comment]
Hi @SamBurgos, can you put together a sample piece of code to illustrate which widget you're using?

**Comment by ghost** [comment]
Greetings @clefebvre , sorry for the delay but I was trying to find the file on another snapshot of the virtual machine I am working on, some sample codes are these (sorry, couldn't format them as code):

 background = GSettingsFileChooser(_("Background"), "x.dm.slick-greeter", "background")    background.set_tooltip_text(_("Set the background picture of the greeter"))
    section.add_row(background)

background_color = GSettingsColorChooser(_("Background color"), "x.dm.slick-greeter", "background-color")
background_color.set_tooltip_text(_("Set the background color of the greeter"))
section.add_row(background_color)

user_background = GSettingsSwitch(_("Draw user backgrounds"), "x.dm.slick-greeter", "draw-user-backgrounds")
user_background.set_tooltip_text(_("When a user is selected, show that user's background."))
section.add_row(user_background)

hidpi_support = GSettingsComboBox(_("HiDPI support"), "x.dm.slick-greeter", "enable-hidpi", hidpi_options)
hidpi_support.set_tooltip_text(_("Support for high pixel density and Retina displays, usually known as 4K."))
section.add_row(hidpi_support)

**Comment by ghost** [comment]
![Screenshot from 2019-06-15 19-32-55](https://user-images.githubusercontent.com/1509924/59557993-b83e2600-8fa4-11e9-8267-60b5b9fce630.png)

![Screenshot from 2019-06-15 19-32-17](https://user-images.githubusercontent.com/1509924/59557994-b83e2600-8fa4-11e9-81f3-96ab0cbaa660.png)

![Screenshot from 2019-06-15 19-31-50](https://user-images.githubusercontent.com/1509924/59557995-b83e2600-8fa4-11e9-8e52-771114c5c898.png)

![Screenshot from 2019-06-15 19-31-13](https://user-images.githubusercontent.com/1509924/59557996-b83e2600-8fa4-11e9-8525-aa2e9499cc8d.png)

**Comment by collinss** [comment]
@SamBurgos You can set a tooltip as one of the arguments in the constructor like so:

```
tooltip = "Set the background picture of the greeter"
background = GSettingsFileChooser(("Background"), "x.dm.slick-greeter", "background", tooltip=tooltip)
section.add_row(background)

tooltip = "Set the background color of the greeter"
background_color = GSettingsColorChooser(("Background color"), "x.dm.slick-greeter", "background-color", tooltip=tooltip)
section.add_row(background_color)

tooltip = "When a user is selected, show that user's background."
user_background = GSettingsSwitch(("Draw user backgrounds"), "x.dm.slick-greeter", "draw-user-backgrounds", tooltip=tooltip)
section.add_row(user_background)

tooltip = "Support for high pixel density and Retina displays, usually known as 4K."
hidpi_support = GSettingsComboBox(("HiDPI support"), "x.dm.slick-greeter", "enable-hidpi", hidpi_options, tooltip=tooltip)
section.add_row(hidpi_support)
```

**Comment by ghost** [comment]
@collinss Thanks for the information, I just want to know if the code works in case I want that tooltip translated, so far what I have been using allows me to translate but I am not sure if it is possible for a translation as well, other than that it works fine

**Comment by clefebvre** [comment]
You'd translate the tooltip yourself before feeding it to the widget.

```
tooltip = _("Support for high pixel density and Retina displays, usually known as 4K.")
hidpi_support = GSettingsComboBox(("HiDPI support"), "x.dm.slick-greeter", "enable-hidpi", hidpi_options, tooltip=tooltip)
section.add_row(hidpi_support)
```
